### PR TITLE
A support for dmesg from newer kernels

### PR DESCRIPTION
**Pull request by pvalsecc**
Looks like EKS upgraded their kernel versions (5.4.156) and in those,
the OOM messages are totally different.
This adds support for that.

And the output of kubernetes is slightly changed around the status of
terminated containers. Adapted to that as well.

Still supports older kernels and kubernetes.

### CODE REVIEW

**Comment by sbrunner** [comment]
Looks good, but shouldn't we add some tests?

**Comment by pvalsecc** [comment]
Yeah, I wanted to do that, but since there are no tests in place for this thing, I didn't know how to add them. I don't know this c2cci thing.
The stupid guy that created es-oom-exporter should have put in place tests from the beginning ;-)
If you put in place a dummy test that is run by the CI, I'll add tests for the parts I've changed. Deal? If it's pytest, it would be great.

**Comment by sbrunner** [comment]
> Yeah, I wanted to do that, but since there are no tests in place for this thing, I didn't know how to add them. I don't know this c2cci thing.

The test will be completely independent to c2cciutils :-)

> The stupid guy that created es-oom-exporter should have put in place tests from the beginning ;-)

lol

> If you put in place a dummy test that is run by the CI, I'll add tests for the parts I've changed. Deal? If it's pytest, it would be great.

I will have a look on this but not on this end of year, Tel me If you need it before :-)

**Comment by pvalsecc** [comment]
OK, I've added tests.

**Comment by sbrunner** [comment]
Many thanks, is it ready to be merged? For me yes :-)

**Pull request merged**
